stages:
  - init
  - install_deps
  - test
  
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

init:
  stage: init
  only:
    - develop
    - master
  variables:
    REPORT_PATH: '/devdata/tests-report'
    CLEAR_FILE_TIME: '3600*24*5'
  script:
    - cd ${REPORT_PATH}
    - pwd
    - find . -type f -name "report_*.html" -o -name "report_*.json" | awk -F'/' '{print $2}'   | awk -F'_' '{print $2}' | awk -F'.' '{tstamp1=mktime(substr($1,1,4)" "substr($1,5,2)" "substr($1,7,2)" "substr($1,9,2)" "substr($1,11,2)" "substr($1,13,2));if (systime() - tstamp1 > ${CLEAR_FILE_TIME} ) print $1;}' 
    - cd ${CI_PROJECT_DIR}
    - pwd
    
install_deps:
  stage: install_deps
  only:
    - develop
    - master
  script:
    - npm install --sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
  
test:
  stage: test
  only:
    - develop
    - master
  script:
    - npm run testreport