stages:
  - install_deps
  - test
  
cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

install_deps:
  stage: install_deps
  only:
    - develop
    - master
  script:
    - npm install --sass_binary_site=https://npm.taobao.org/mirrors/node-sass/
  
test:
  stage: test
  only:
    - develop
    - master
  script:
    - npm run testreport